#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20 and:
# Displays 4 and then bad luck from China on 4th  iteration
# Displays 9 and then bad luck from Japan on 9th iteration
# Displays 17 and then bad luck from Italy on 17th iteration

i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
	     4) echo "bad luck from China"
	     	;;
	     9) echo "bad luck from Japan"
	        ;;
	     17) echo "bad luck from Italy"
	        ;;
        esac
	i=$((i+1))
done
